### ISSUE TITLE
Make sure all of the latest Telegram API updates are in

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#360]
https://core.telegram.org/bots/api-changelog

Just a checklist to make sure that all new features are included.
*Putting the games on this list too, which should be implemented at some point! (#308)*

## December 4, 2016 - Bot API 2.3.1

- [x] Use the new field max_connections in setWebhook to optimize your bot's server load
- [x] Use allowed_updates in setWebhook and getUpdates to selectively subscribe to updates of a certain type. Among other things, this allows you to stop getting updates about new posts in channels where your bot is an admin.
- [x] deleteWebhook moved out of setWebhook to get a whole separate method for itself.

## November 21, 2016 - Bot API 2.3

- [x] Your bot can now get updates about posts in channels. Added new fields channel_post and edited_channel_post to Update.
- [x] Added the new field forward_from_message_id to Message. (#364)
- [x] Added the new parameter cache_time to answerCallbackQuery. Will eventually work in Telegram apps — somewhere after version 3.14, maybe 3.15. (#364)
- [x] Renamed hide_keyboard to remove_keyboard in ReplyKeyboardRemove for clarity. hide_keyboard will still work for a while for backward compatibility.
- [ ] You can now update high scores to a lower value by using the new force parameter in setGameScore. Handy for punishing cheaters or fixing errors in your game's High Score table.
- [ ] Starting today, messages with high scores will be updated with new high scores by default. Use disable_edit_message in setGameScore if you don't want this.
- [ ] The edit_message parameter from setGameScore is no longer in use. For backward compatibility, it will be taken into account for a while, unless disable_edit_message is passed explicitly.

## October 3, 2016 - Bot API 2.2

- [x] New method getWebhookInfo to check current webhook status.
- [x] Added the option to specify an HTTP URL for a file in all methods where InputFile or file_id can be used (except voice messages). Telegram will get the file from the specified URL and send it to the user. Files must be smaller than 5 MB for photos and smaller than 20 MB for all other types of content.
- [x] Added new field switch_inline_query_current_chat in InlineKeyboardButton.
- [x] Added caption fields to sendAudio, sendVoice, InlineQueryResultAudio, InlineQueryResultVoice, InlineQueryResultCachedAudio, and InlineQueryResultCachedVoice. (#364)
- [x] New field all_members_are_administrators in the Chat object. (#364)
- [ ] Use the new url parameter in answerCallbackQuery to create buttons that open your bot with user-specific parameters.
- [ ] New method sendGame, new object InlineQueryResultGame, new field game in Message.
- [ ] New parameter url in answerCallbackQuery. Create a game and accept the conditions using Botfather to send custom urls that open your games for the user.
- [ ] New field callback_game in InlineKeyboardButton, new fields game_short_name and chat_instance in CallbackQuery, new object CallbackGame.
- [ ] New methods setGameScore and getGameHighScores.

## May 25, 2016

- [x] Inline keyboards may now be used in group chats. Channels coming soon. 
(inline keyboards in channels were silently enabled by Telegram)

## May 22, 2016 - Bot API 2.1

- [x] Added new methods: getChat, leaveChat, getChatAdministrators, getChatMember, getChatMembersCount.
- [x] Added support for edited messages and new mentions from Telegram v.3.9. New fields: edited_message in Update, edit_date in Message, user in MessageEntity. New value text_mention for the type field in MessageEntity.

**Comment by jacklul** [comment]
> Added the option to specify an HTTP URL for a file in all methods where InputFile or file_id (...)

I don't think this requires any code changes since you can simply do ```Request::sendPhoto([chat_id' => $chat_id, 'photo' => $file_url]);``` to achieve new functionality.

>  Inline keyboards may now be used in group chats. Channels coming soon.

They were enabled some time ago and work without any changes.

> Added more tools for group administrator bots. (...) 

This can be removed from the list as it's just summary of update.

From what I see all that's left is GameAPI things.

**Comment by noplanman** [comment]
Feel free to update my comment above to keep it up to date 👍 

Yep, looks like the games is the main thing that's missing, nice!

**Comment by noplanman** [comment]
Since only the games things are missing, a separate issue will be made for that specifically.

**Comment by noplanman** [comment]
Hi @SirDerpington, take a look here #732, we'd highly appreciate your testing of it :tada:
